using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Digigraf.Rat.Dominio.Entidades.SIGA
{
  public class SA1110
    {
        public string A1_FILIAL { get; set; }
        public string A1_COD { get; set; }
        public string A1_LOJA { get; set; }
        public string A1_NOME { get; set; }
        public string A1_PESSOA { get; set; }
        public string A1_NREDUZ { get; set; }
        public string A1_END { get; set; }
        public string A1_BAIRRO { get; set; }
        public string A1_TIPO { get; set; }
        public string A1_EST { get; set; }
        public string A1_ESTADO { get; set; }
        public string A1_CEP { get; set; }
        public string A1_COD_MUN { get; set; }
        public string A1_MUN { get; set; }
        public string A1_REGIAO { get; set; }
        public string A1_DSCREG { get; set; }
        public string A1_NATUREZ { get; set; }
        public string A1_IBGE { get; set; }
        public string A1_ENDCOB { get; set; }
        public string A1_DDI { get; set; }
        public string A1_DDD { get; set; }
        public string A1_ENDREC { get; set; }
        public string A1_ENDENT { get; set; }
        public string A1_TEL { get; set; }
        public string A1_TRIBFAV { get; set; }
        public string A1_CONTATO { get; set; }
        public string A1_FAX { get; set; }
        public string A1_CGC { get; set; }
        public string A1_TELEX { get; set; }
        public string A1_PFISICA { get; set; }
        public string A1_INSCR { get; set; }
        public string A1_INSCRM { get; set; }
        public string A1_PAIS { get; set; }
        public string A1_VEND { get; set; }
        public double A1_COMIS { get; set; }
        public string A1_CONTA { get; set; }
        public string A1_BCO1 { get; set; }
        public string A1_BCO2 { get; set; }
        public string A1_BCO3 { get; set; }
        public string A1_BCO4 { get; set; }
        public string A1_BCO5 { get; set; }
        public string A1_TRANSP { get; set; }
        public string A1_TPFRET { get; set; }
        public string A1_COND { get; set; }
        public double A1_DESC { get; set; }
        public string A1_PRIOR { get; set; }
        public string A1_RISCO { get; set; }
        public double A1_LC { get; set; }
        public string A1_VENCLC { get; set; }
        public string A1_CLASSE { get; set; }
        public double A1_LCFIN { get; set; }
        public double A1_MOEDALC { get; set; }
        public double A1_MSALDO { get; set; }
        public double A1_MCOMPRA { get; set; }
        public double A1_METR { get; set; }
        public string A1_PRICOM { get; set; }
        public string A1_ULTCOM { get; set; }
        public double A1_NROCOM { get; set; }
        public string A1_FORMVIS { get; set; }
        public double A1_TEMVIS { get; set; }
        public string A1_ULTVIS { get; set; }
        public string A1_TMPVIS { get; set; }
        public string A1_TMPSTD { get; set; }
        public string A1_CLASVEN { get; set; }
        public string A1_MENSAGE { get; set; }
        public double A1_SALDUP { get; set; }
        public string A1_RECISS { get; set; }
        public double A1_SALPEDL { get; set; }
        public double A1_NROPAG { get; set; }
        public string A1_TRANSF { get; set; }
        public string A1_SUFRAMA { get; set; }
        public double A1_ATR { get; set; }
        public double A1_VACUM { get; set; }
        public double A1_SALPED { get; set; }
        public double A1_TITPROT { get; set; }
        public string A1_DTULTIT { get; set; }
        public double A1_CHQDEVO { get; set; }
        public string A1_DTULCHQ { get; set; }
        public double A1_MATR { get; set; }
        public double A1_MAIDUPL { get; set; }
        public string A1_TABELA { get; set; }
        public string A1_INCISS { get; set; }
        public double A1_SALDUPM { get; set; }
        public double A1_PAGATR { get; set; }
        public string A1_CXPOSTA { get; set; }
        public string A1_ATIVIDA { get; set; }
        public string A1_CARGO1 { get; set; }
        public string A1_CARGO2 { get; set; }
        public string A1_CARGO3 { get; set; }
        public string A1_SUPER { get; set; }
        public string A1_RTEC { get; set; }
        public double A1_ALIQIR { get; set; }
        public string A1_RG { get; set; }
        public string A1_OBSERV { get; set; }
        public string A1_CALCSUF { get; set; }
        public string A1_DTNASC { get; set; }
        public double A1_SALPEDB { get; set; }
        public string A1_CLIFAT { get; set; }
        public string A1_GRPTRIB { get; set; }
        public string A1_BAIRROC { get; set; }
        public string A1_CEPC { get; set; }
        public string A1_MUNC { get; set; }
        public string A1_ESTC { get; set; }
        public string A1_CEPE { get; set; }
        public string A1_BAIRROE { get; set; }
        public string A1_MUNE { get; set; }
        public string A1_ESTE { get; set; }
        public string A1_SATIV1 { get; set; }
        public string A1_SATIV2 { get; set; }
        public string A1_CODLOC { get; set; }
        public string A1_TPISSRS { get; set; }
        public string A1_CODPAIS { get; set; }
        public string A1_TPESSOA { get; set; }
        public string A1_SATIV3 { get; set; }
        public string A1_SATIV4 { get; set; }
        public string A1_SATIV5 { get; set; }
        public string A1_SATIV6 { get; set; }
        public string A1_SATIV7 { get; set; }
        public string A1_SATIV8 { get; set; }
        public string A1_CODMARC { get; set; }
        public string A1_CODAGE { get; set; }
        public double A1_COMAGE { get; set; }
        public string A1_TIPCLI { get; set; }
        public string A1_EMAIL { get; set; }
        public string A1_DEST_1 { get; set; }
        public string A1_DEST_2 { get; set; }
        public string A1_CODMUN { get; set; }
        public string A1_HPAGE { get; set; }
        public string A1_DEST_3 { get; set; }
        public string A1_CBO { get; set; }
        public string A1_CNAE { get; set; }
        public string A1_CONDPAG { get; set; }
        public double A1_DIASPAG { get; set; }
        public string A1_OBS { get; set; }
        public string A1_AGREG { get; set; }
        public string A1_CODHIST { get; set; }
        public string A1_RECINSS { get; set; }
        public string A1_RECCOFI { get; set; }
        public string A1_RECCSLL { get; set; }
        public string A1_RECPIS { get; set; }
        public string A1_TIPPER { get; set; }
        public double A1_SALFIN { get; set; }
        public double A1_SALFINM { get; set; }
        public string A1_CONTAB { get; set; }
        public string A1_B2B { get; set; }
        public string A1_GRPVEN { get; set; }
        public string A1_CLICNV { get; set; }
        public string A1_INSCRUR { get; set; }
        public string A1_MSBLQL { get; set; }
        public string A1_SITUA { get; set; }
        public string A1_NUMRA { get; set; }
        public string A1_SUBCOD { get; set; }
        public string A1_CDRDES { get; set; }
        public string A1_FILDEB { get; set; }
        public string A1_CODFOR { get; set; }
        public string A1_ABICS { get; set; }
        public string A1_BLEMAIL { get; set; }
        public string A1_TIPOCLI { get; set; }
        public string A1_VINCULO { get; set; }
        public string A1_DTINIV { get; set; }
        public string A1_DTFIMV { get; set; }
        public string A1_LOCCONS { get; set; }
        public string A1_CODMUNE { get; set; }
        public double A1_PERFIL { get; set; }
        public string A1_HRTRANS { get; set; }
        public string A1_UNIDVEN { get; set; }
        public string A1_TIPPRFL { get; set; }
        public string A1_PRF_VLD { get; set; }
        public string A1_PRF_COD { get; set; }
        public string A1_REGPB { get; set; }
        public string A1_USADDA { get; set; }
        public string A1_SIMPLES { get; set; }
        public string A1_CTARE { get; set; }
        public string A1_FRETISS { get; set; }
        public string A1_CODSIAF { get; set; }
        public string A1_CEINSS { get; set; }
        public string A1_REGESIM { get; set; }
        public string A1_IPWEB { get; set; }
        public double A1_PERCATM { get; set; }
        public string A1_IRBAX { get; set; }
        public string A1_ENDNOT { get; set; }
        public string A1_RESERVE { get; set; }
        public string A1_NIF { get; set; }
        public string A1_IDHIST { get; set; }
        public string A1_INDRET { get; set; }
        public string A1_ABATIMP { get; set; }
        public string A1_CONTRIB { get; set; }
        public string A1_INCULT { get; set; }
        public string A1_TDA { get; set; }
        public string A1_ORIGEM { get; set; }
        public string A1_ENTID { get; set; }
        public string A1_MINIRF { get; set; }
        public string A1_TIMEKEE { get; set; }
        public string A1_RECIRRF { get; set; }
        public string A1_COMPLEM { get; set; }
        public string A1_MATFUN { get; set; }
        public string A1_FILTRF { get; set; }
        public string A1_FOMEZER { get; set; }
        public string A1_CODFID { get; set; }
        public string A1_SIMPNAC { get; set; }
        public string A1_ALIFIXA { get; set; }
        public string A1_RFABOV { get; set; }
        public string A1_TPDP { get; set; }
        public double A1_PERFECP { get; set; }
        public string A1_RFACS { get; set; }
        public string A1_TPJ { get; set; }
        public string A1_CRDMA { get; set; }
        public string A1_PRSTSER { get; set; }
        public string A1_RECFET { get; set; }
        public string A1_IENCONT { get; set; }
        public string A1_ORIGCT { get; set; }
        public string A1_HRCAD { get; set; }
        public string A1_ENTORI { get; set; }
        public string A1_DTCAD { get; set; }
        public string A1_IMGUMOV { get; set; }
        public string A1_RESFAT { get; set; }
        public string A1_IDESTN { get; set; }
        public double A1_NVESTN { get; set; }
        public string A1_CLIPRI { get; set; }
        public string A1_LOJPRI { get; set; }
        public string A1_TPCAMP { get; set; }
        public string A1_CHVCAM { get; set; }
        public string A1_INOVAUT { get; set; }
        public string A1_TPNFSE { get; set; }
        public string A1_OUTRMUN { get; set; }
        public string A1_CODSEG { get; set; }
        public string A1_TPREG { get; set; }
        public string A1_MSEXP { get; set; }
        public string A1_ISSRSLC { get; set; }
        public string A1_USERLGA { get; set; }
        public string A1_HREXPO { get; set; }
        public string A1_USERLGI { get; set; }
        public string A1_TPMEMB { get; set; }
        public string A1_CODTER { get; set; }
        public string A1_CODMEMB { get; set; }
        public string A1_SANGUE { get; set; }
        public string A1_CONT { get; set; }
        public string A1_R_G { get; set; }
        public string A1_SOC_A { get; set; }
        public string A1_SOC_B { get; set; }
        public string A1_SOC_C { get; set; }
        public string A1_SOC_D { get; set; }
        public string A1_SOC_E { get; set; }
        public string A1_BAIRCOB { get; set; }
        public string A1_MUNCOB { get; set; }
        public string A1_ESTCOB { get; set; }
        public string A1_CEPCOB { get; set; }
        public string A1_EBAIRRO { get; set; }
        public string A1_EMUN { get; set; }
        public string A1_EEST { get; set; }
        public string A1_ECEP { get; set; }
        public string A1_VEND2 { get; set; }
        public string A1_EMISSAO { get; set; }
        public string A1_LEASING { get; set; }
        public string A1_MIDIA { get; set; }
        public string A1_PRZMAXD { get; set; }
        public string D_E_L_E_T_ { get; set; }
        public int R_E_C_N_O_ { get; set; }
        public int R_E_C_D_E_L_ { get; set; }
        public string A1_INDUSTR { get; set; }
        public string A1_XCTSUP { get; set; }
        public string A1_XESUP { get; set; }
        public string A1_XT1SUP { get; set; }
        public string A1_XCELSUP { get; set; }
        public string A1_XT2SUP { get; set; }
        public string A1_XCTMAQ { get; set; }
        public string A1_XEMAQ { get; set; }
        public string A1_XT1MAQ { get; set; }
        public string A1_XT2MAQ { get; set; }
        public string A1_CELMAQ { get; set; }
    }
}
